### ISSUE TITLE
Transformation GPS - Map coordinates

### ISSUE THREAD

**Issue by TBdt38** [midemig/gps_amcl#1]
Thanks for the nice paper. I have a question regarding the mapping phase. 
How do you keep the correspondence for any location between the GPS coordinates and the map points which is in local coordinates by definition?
Do you only use the initial pose transform GPS-map frame and use it all along the path? 
If you apply SLAM algorithm, it means the point clouds from lidars are optimized and aligned at each time step using gmapping i suppose. 
So, how to you keep trace of the transform global coordinate / local coordinate for the complete map?
Thanks!

**Comment by midemig** [comment]
The map is generated with the GPS localization, considering the first GPS position as the origin.
I use gmapping to create the map, but it is configured to highly rely on GPS localization to avoid the problem you mention. So, basically what gmapping does is to accumulate the laser points using GPS odometry.

**Comment by salbatarni** [comment]
can it be used to follow a specific gps coordinates?

> The map is generated with the GPS localization, considering the first GPS position as the origin. I use gmapping to create the map, but it is configured to highly rely on GPS localization to avoid the problem you mention. So, basically what gmapping does is to accumulate the laser points using GPS odometry.
