### ISSUE TITLE
LaserScan score absent in new weights calculation

### ISSUE THREAD

**Issue by dimaxano** [midemig/gps_amcl#3]
Hi @midemig!
Thank you for your work!

I have a question regarding the implementation
As per my understanding, we should use particle score at the calculation of the new weight. But seems, it is [not used](https://github.com/midemig/gps_amcl/blob/4cca5ea1da5463ac28806c03cf12621ceb841090/src/amcl/pf/pf.c#L432). 

Is it made by purpose?

**Comment by midemig** [comment]
Hi!
The particle score is represented by its weight which is calculated in amcl_laser.cpp and later updated in pf.cpp.
The score variable is not used, so I have deleted it.
Tank you!
